version: '3'
services:
  server:
    image: cs-server:latest
    ports:
    - '${SERVER_PORT}:80'
    networks:
    - laracasts-forum
    depends_on:
    - web
    - api
  web:
    image: laracasts-forum-web:latest
    ports:
    - '${WEB_PORT}:3000'
    environment:
      PUBLIC_PORT: "${WEB_PORT}"
    networks:
    - laracasts-forum
    volumes:
    - ./web:/usr/src/web
    - web_node_modules:/usr/src/web/node_modules
  api:
    image: laracasts-forum-api:latest
    ports:
    - '${API_PORT}:8080'
    environment:
      APP_ENV: "${APP_ENV}"
      DB_HOST: "${DB_HOST}"
      DB_DATABASE: "${DB_NAME}"
      DB_USERNAME: "${DB_USER}"
      DB_PASSWORD: "${DB_PASS}"
    networks:
    - laracasts-forum
    volumes:
    - ./api:/usr/src/api
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    ports:
    - '${DB_PORT}:3306'
    networks:
    - laracasts-forum
  e2e:
    build:
      context: ./e2e
      dockerfile: docker/Dockerfile
    image: laracasts-forum-e2e
    volumes:
      - ./e2e:/usr/src/e2e
      - e2e_node_modules:/usr/src/e2e/node_modules
    networks:
      - laracasts-forum
networks:
  laracasts-forum:
    driver: bridge
volumes:
  e2e_node_modules:
  web_node_modules:
  api_vendor_files: